apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: kubedeploytest
spec:
  selector:
    matchLabels:
      app: kubedeploytest
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: kubedeploytest
    spec:
      containers:
        - name: kubedeploytest
          image: thirukjpt/kubedeploytest:1.0
# Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 
# The port that the container is running on in the cluster
#          env:
#            - name: DB_HOST
#             value: mysql
#           - name: DB_NAME
#             value: thirumala
#           - name: DB_USERNAME
#             value: root
#           - name: DB_PASSWORD
#             value: root
---
apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: kubedeploytest-svc
spec:
  selector:
    app: kubedeploytest
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.   